### ISSUE TITLE
[Question] the 'variable-length attention operator in flash attention'

### ISSUE THREAD

**Issue by jonasjunzhang** [Oryx-mllm/Oryx#2]
Hi there! It is mentioned in the paper that "variable-length attention operator provided in flash attention (Dao et al., 2022) to compute the attention for each visual input within the batch independently". However, I read the code in [here](https://github.com/Oryx-mllm/Oryx/blob/a36a906b98584002c835a36794deb57f32a9a0f0/oryx/model/oryx_arch.py#L97) and did not find code related to this variable-length attention operator, and the high-resolution features are encoded with a for loop. Did I miss something?
Thank you!

**Comment by liuzuyan** [comment]
Hi, thanks for your interest in our work! We pre-process the input images into a list in the code you implemented and then forward the whole list to OryxViT for batch computation [here](https://github.com/Oryx-mllm/Oryx/blob/main/oryx/model/oryx_arch.py#L144). The variable-length attention is operated [here](https://github.com/Oryx-mllm/Oryx/blob/main/oryx/model/oryx_arch.py#L97). Feel free to ask should you have further questions!

**Comment by Yxxxb** [comment]
@liuzuyan 
Hi zuyan, great work!!!

I would like to know if the "variable-length" mentioned in this issue can support different token lengths within a batch? Because as far as I know, models such as LLaVA are implemented by padding. If the output token length of OrysViT varies depending on the image resolution, not-padding will cause parallel problems, and padding will increase FLOPS.

It would be great if you can help me point out the code that handles this part!
Thanks!

**Comment by jonasjunzhang** [comment]
Ah thanks! I read the code again and figured it out.
