### ISSUE TITLE
Question about Variable-length.

### ISSUE THREAD

**Issue by Yxxxb** [Oryx-mllm/Oryx#5]
@liuzuyan 
Hi zuyan, great work!!!

I would like to know if Orys can support different token lengths within a batch or how to deal with it? 
For example, a batch length is 2, and due to different image sizes, the visual token lengths are 500 and 50 respectively. Will this cause parallel problems? As far as I know, models such as LLaVA are implemented by padding. If the output token length of OrysViT varies depending on the image resolution, not-padding will cause parallel problems, and padding will increase FLOPS.

I noticed that you still chose to use padding in the code:
https://github.com/Oryx-mllm/Oryx/blob/a36a906b98584002c835a36794deb57f32a9a0f0/oryx/model/oryx_arch.py#L259

It would be great if you can help me point out the code that handles this part!
Thanks!

**Comment by liuzuyan** [comment]
Hi, thanks for your interest in our work!
In our implementation, we also pad tokens (visual + language) in batches following previous works. That is because we use multiple GPUs (64 in our experiments) for training, therefore even if we compute each sequence as its original length, the overall training time is still determined by the longest sequence, and the padding operation will not increase the overall training time.
